# Generated by Django 4.2.2 on 2024-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0003_studentinternship_proctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutorial',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
